name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Hellow world action
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v1
      - uses: ./action-a
        with:
          My_NAME: "Mona"