on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - id: hello_actions
      uses: actions/hello_action@v1
      with:
        who-to-greet: 'Nour Megahed'
    - run: echo random-number ${{ steps.hello_actions.outputs.random-number }}
      shell: bash