name: A workflow for my Hello World file
on: push

jobs:
  build:
    name: Testing Docker Builds
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Testing executing docker files
      - run: |
          docker build -t testing:latest .
          docker run --detach --name testing testing:latest